services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: dslr
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
  
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "8501:8501"
    volumes:
      - .:/app

networks:
  default:
    driver: bridge 

volumes:
  db_data:
    driver: local